apiVersion: v2
appVersion: 24.2.3
description: A Helm chart for Kubernetes CloudBeaver
name: cloudbeaver
type: application
version: 1.0.0
dependencies:
  - name: common
    version: 2.26.0
    repository: oci://registry-1.docker.io/bitnamicharts